### Create a new movie
POST {{Movies.API_HostAddress}}/api/movies
Content-Type: application/json

{
  "title": "Inception",
  "yearOfRelease": 2010,
  "genres": ["Action", "Sci-Fi"]
}

### Get movie by ID
GET {{Movies.API_HostAddress}}/api/movies/{{Id}}
Content-Type: application/json

### Get all movies
GET {{Movies.API_HostAddress}}/api/movies
Content-Type: application/json

### Update a movie
PUT {{Movies.API_HostAddress}}/api/movies/{{id}}
Content-Type: application/json

{
  "title": "Inception Updated",
  "yearOfRelease": 2010,
  "genres": ["Action", "Sci-Fi", "Thriller"]
}